const reports = {

    async renderPage() {

        document.getElementById("pageContent").innerHTML = `
            <section class="section">
                <div class="toolbar">
                    <div>
                        <h3>Reports</h3>
                        <p class="muted">Admin reports generated by the backend.</p>
                    </div>
                    <div class="toolbar-group">
                        <select id="reportType">
                            <option value="department">Department</option>
                            <option value="category">Category</option>
                            <option value="monthly">Monthly</option>
                            <option value="closed">Closed Complaints</option>
                            <option value="pending">Pending Complaints</option>
                        </select>
                        <button id="exportReport" class="secondary-button" type="button">Export CSV</button>
                    </div>
                </div>
                <div id="reportOutput">${loading()}</div>
            </section>
        `;

        await this.load("department");

        document.getElementById("pageContent").onchange = event => {
            if (event.target.id === "reportType") this.load(event.target.value);
        };

        document.getElementById("pageContent").onclick = event => {
            if (event.target.id === "exportReport") this.export();
        };

    },

    current: [],

    async load(type) {

        try {
            const response = await api.get(`/reports/${type}`);
            this.current = response.report || response.complaints || [];
            this.render(type, this.current);
        } catch (error) {
            showMessage(error.message, "error");
        }

    },

    render(type, data) {

        const output = document.getElementById("reportOutput");

        if (!data.length) {
            output.innerHTML = `<p class="muted">No report data found.</p>`;
            return;
        }

        if (type === "closed" || type === "pending") {
            output.innerHTML = complaintsTableMarkup(data);
            return;
        }

        output.innerHTML = `
            <div class="table-wrap">
                <table>
                    <thead>
                        <tr>${Object.keys(this.flatten(data[0])).map(key => `<th>${escapeHtml(key)}</th>`).join("")}</tr>
                    </thead>
                    <tbody>
                        ${data.map(row => {
                            const flat = this.flatten(row);
                            return `<tr>${Object.values(flat).map(value => `<td>${escapeHtml(value)}</td>`).join("")}</tr>`;
                        }).join("")}
                    </tbody>
                </table>
            </div>
        `;

    },

    flatten(row) {

        if (row._id && typeof row._id === "object") {
            return {
                year: row._id.year,
                month: row._id.month,
                complaints: row.complaints
            };
        }

        return {
            name: row._id,
            ...Object.fromEntries(Object.entries(row).filter(([key]) => key !== "_id"))
        };

    },

    export() {

        if (!this.current.length) return;
        const rows = this.current.map(row => this.flatten(row));
        csvDownload("report.csv", [
            Object.keys(rows[0]),
            ...rows.map(row => Object.values(row))
        ]);

    }

};

function complaintsTableMarkup(items) {

    return `
        <div class="table-wrap">
            <table>
                <thead><tr><th>ID</th><th>Employee</th><th>Category</th><th>Status</th><th>Created</th></tr></thead>
                <tbody>
                    ${items.map(c => `
                        <tr>
                            <td><strong>${escapeHtml(c.complaintId)}</strong></td>
                            <td>${escapeHtml(c.employeeName)}</td>
                            <td>${escapeHtml(c.category)}</td>
                            <td>${badge(c.status)}</td>
                            <td>${formatDate(c.createdAt)}</td>
                        </tr>
                    `).join("")}
                </tbody>
            </table>
        </div>
    `;

}
